[2024-10-01T15:50:49.143+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-01T15:50:49.160+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_pipeline.s3_upload manual__2024-10-01T15:50:44.582505+00:00 [queued]>
[2024-10-01T15:50:49.172+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_pipeline.s3_upload manual__2024-10-01T15:50:44.582505+00:00 [queued]>
[2024-10-01T15:50:49.174+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-01T15:50:49.189+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-10-01 15:50:44.582505+00:00
[2024-10-01T15:50:49.196+0000] {standard_task_runner.py:72} INFO - Started process 78 to run task
[2024-10-01T15:50:49.199+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_pipeline', 's3_upload', 'manual__2024-10-01T15:50:44.582505+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpnhaixfiu']
[2024-10-01T15:50:49.202+0000] {standard_task_runner.py:105} INFO - Job 40: Subtask s3_upload
[2024-10-01T15:50:49.248+0000] {task_command.py:467} INFO - Running <TaskInstance: reddit_pipeline.s3_upload manual__2024-10-01T15:50:44.582505+00:00 [running]> on host 0e63f9394fb3
[2024-10-01T15:50:49.329+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Haziq' AIRFLOW_CTX_DAG_ID='reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T15:50:44.582505+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-01T15:50:44.582505+00:00'
[2024-10-01T15:50:49.332+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-01T15:50:49.360+0000] {logging_mixin.py:190} INFO - connected successfully to s3
[2024-10-01T15:50:51.329+0000] {logging_mixin.py:190} INFO - The AWS Access Key Id you provided does not exist in our records.
[2024-10-01T15:50:51.550+0000] {logging_mixin.py:190} INFO - The AWS Access Key Id you provided does not exist in our records.
[2024-10-01T15:50:51.552+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-01T15:50:51.561+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-01T15:50:51.563+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=reddit_pipeline, task_id=s3_upload, run_id=manual__2024-10-01T15:50:44.582505+00:00, execution_date=20241001T155044, start_date=20241001T155049, end_date=20241001T155051
[2024-10-01T15:50:51.586+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-01T15:50:51.604+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-01T15:50:51.607+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
